### ISSUE TITLE
File PDF kurang sesuai

### ISSUE THREAD

**Issue by NaofalMufid** [NaofalMufid/gatekna#1]
Ukuran file pdf(kontenya) penatan dan banyak raung kosong dalam sau halaman. jadi saya ingin sau halaman bisa dibua untuk beberapa tiket.

**Comment by ilosaurus** [comment]
sy coba handle gan

**Comment by yogs22** [comment]
Masih bisa handel ?

**Comment by ilosaurus** [comment]
Saya coba handle

**Comment by yogs22** [comment]
![image](https://user-images.githubusercontent.com/25165999/46514795-41d01c80-c88a-11e8-9749-058002e8f86e.png)

**Comment by NaofalMufid** [comment]
Boleh boleh, agak berantakan soalnya

**Comment by ilosaurus** [comment]
Bisa liat layout yg d harapkan?
